version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
  api:
    build:
      context: ./griot_backend/
    ports:
      - "8000:8000"
    volumes:
      - ./griot_backend:/api
    entrypoint: ["./entrypoint.sh"]
