version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: dbname
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
  api:
    build:
      context: ./griot_backend/
    volumes:
      - ./griot_backend:/api
    environment:
      - DJANGO_SETTINGS_MODULE=griot_backend.settings_dev
      - ENV=dev
    entrypoint: ["./entrypoint.sh"]
  nginx:
    build:
      context: ./nginx/
    ports:
      - "80:80"
    volumes:
      - ./griot_backend/static:/app/static
      - ./griot_backend/media:/app/media
    depends_on:
      - api